language: java
jdk:
  - openjdk8

install: true

cache:
  directories:
    - "$HOME/.m2"

before_script:
  - echo "MAVEN_OPTS='-Xmx1024m -XX:MaxMetaspaceSize=256m'" > ~/.mavenrc

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"